### PR TITLE
ENH support raygun4php SDK v2

### LINKED ISSUE #59: Update for Raygun PHP SDK v2 when it is released
The PHP SDK is preparing for its v2 release, which includes some breaking changes (notably https://github.com/MindscapeHQ/raygun4php/pull/117 re: client instantiation).

Just a placeholder for now, but when it's tagged it'd be a good idea to update this module to either allow both versions to be installed, or release a new minor version with an updated upstream dependency.

### PR DESCRIPTION
**Pull request by GuySartorelli**
Fixes #59 

This PR provides support for raygun4php sdk V2 while allowing anyone who for whatever reason might want/need to stay on sdk V1 (e.g. super old PHP versions) to keep up to date with this module.

The only breaking changes that I can see for sdk V2 vs V1 are in the constructor so I think this should be safe.
I have tried both versions of the SDK with this PR and have had no issues with either.

### CODE REVIEW

**Comment by GuySartorelli** [comment]
@robbieaverill @brynwhyman Any chance at having some eyes across this? It would be great if we could have this merged and tagged before/with the SS 4.10 release. That will make it easy to update this module at the same time as updating framework in our sites.

There's also some new filtering functionality about to get a stable tag in SDK v2 so it'd be great to be able to take advantage of that.

**Comment by brynwhyman** [comment]
Hey @GuySartorelli I'm no longer working with Silverstripe so can't as easily find folks to help sorry. @madmatt perhaps this is something you could please help with?

**Comment by madmatt** [comment]
This looks good to me, thanks and Merry Christmas @GuySartorelli! 🎄

**Comment by madmatt** [comment]
New release 3.5.0 now includes this change along with 3 others from you, thanks again @GuySartorelli! 🎉

**Comment by GuySartorelli** [comment]
Thank you! A great Christmas present 😁

**Pull request merged**
